# Generated by Django 4.0.1 on 2022-01-26 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_Panel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('gmail', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
