# Generated by Django 4.0.1 on 2022-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_panel',
            name='owner_priority_serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
