# Generated by Django 4.0.1 on 2022-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Panel', '0002_owner_panel_owner_priority_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_panel',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
