# Generated by Django 4.0.1 on 2022-02-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Panel', '0005_alter_owner_panel_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_panel',
            name='Facebook_URL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='owner_panel',
            name='Instagram_URL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='owner_panel',
            name='Linkedin_URL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
