# Generated by Django 4.0.1 on 2022-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Panel', '0006_alter_owner_panel_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_panel',
            name='ownership',
            field=models.CharField(default=20, max_length=200),
            preserve_default=False,
        ),
    ]
