# Generated by Django 4.0.1 on 2022-02-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Panel', '0010_remove_owner_panel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_panel',
            name='password',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
