# Generated by Django 4.0.1 on 2022-02-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Panel', '0011_owner_panel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_panel',
            name='password',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
