# Generated by Django 4.0.1 on 2022-02-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Panel', '0012_alter_owner_panel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner_panel',
            name='password',
        ),
    ]
