# Generated by Django 4.0.1 on 2022-02-05 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Panel', '0013_remove_owner_panel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Panel',
            fields=[
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('food_priority_serial', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
