# Generated by Django 4.0.1 on 2022-02-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coders',
            new_name='owner_login',
        ),
    ]
